# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-12-06 19:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('glimpseAPIApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='media',
            name='gif_link',
            field=models.CharField(default='', max_length=245),
            preserve_default=False,
        ),
    ]
